spring:
  application:
    name: ecommerce.shop
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: dexter
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    user:
      name: admin
      password: admin123

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

logging:
  level:
    org:
      springframework:
        security: DEBUG